djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from leads.views import LandingPageView, landing_page, SignupView
from django.contrib import admin
from django.urls import path, include
from leads.views import landing_page
from django.contrib.auth.views import LoginView,LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace="agents")),
    # password reset form template is not being triggered for some reason
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from django.views.generic.list import ListView
from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView

app_name = "leads"
urlpatterns = [
    path('', LeadListView.as_view(), name="lead-list"),
    path('<int:pk>/', LeadDetailView.as_view(), name="lead-detail"),
    path('create/', LeadCreateView.as_view(), name="lead-create"),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name="lead-update"),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name="lead-delete"),


]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE
from django.db.models.expressions import F
from django.db.models.signals import post_save

class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.email


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from django.forms.models import fields_for_model
from .models import Lead, User
from django.contrib.auth.forms import UserCreationForm, UsernameField

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (          
            'first_name',
            'last_name',
            'age',
            'agent',
            )

class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", )
        field_classes = {'username': UsernameField}

leads/views.py
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django import forms
from django.shortcuts import render
from django.views import generic
from .models import Lead, Agent
from .forms import LeadModelForm, LeadForm, CustomUserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from agents.mixins import OrganizerAndLoginRequiredMixin
class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse_lazy("login")

class LandingPageView(generic.TemplateView):
    template_name = "landing.html"


def landing_page(request):
    return render(request, "../templates/landing.html")


class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = "leads/lead_list.html"
    context_object_name = "leads"
    
    def get_queryset(self):
        user=self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization, agent__isnull=False)
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        conetxt = super(LeadListView, self).get_context_data(**kwargs)
        user=self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, 
                agent__isnull=True)
            conetxt.update({
                "unassigned_leads":queryset
            })
        return conetxt

# def lead_list(request):
#     leads = Lead.objects.all()
#     contex={
#         "leads": leads
#     }
#     return render(request, "leads/lead_list.html", contex)

class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "leads/lead_detail.html"
    context_object_name = "lead"
    
    def get_queryset(self):
        user=self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization, agent__isnull=False)
            queryset = queryset.filter(agent__user=user)
        return queryset


# def lead_detail(request, pk):
#     lead = Lead.objects.get(id=pk)
#     context={
#         'lead':lead
#     }
#     return render(request, "leads/lead_detail.html", context)

class LeadCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = "leads/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse_lazy("leads:lead-list")

    def form_valid(self,form):
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead", 
            from_email="cy0378@gmail.com",
            recipient_list=["yuchengzhi2673@hotmail.com"]

        )
        return super(LeadCreateView, self).form_valid(form)

# def lead_create(request):
#     form = LeadModelForm()
#     if request.method == "POST":
#         # print(request.POST)
#         form = LeadModelForm(request.POST)
#         if form.is_valid():
#             # print(form.cleaned_data)
#             form.save()
#             return redirect("/leads")
#     context = {
#         "form": form
#     }
#     return render(request, "leads/lead_create.html",context)
class LeadUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name = "leads/lead_update.html"
    form_class = LeadModelForm
    def get_queryset(self):
        user=self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        return queryset
    def get_success_url(self):
        return reverse_lazy("leads:lead-list")
# def lead_update(request, pk):
#     lead = Lead.objects.get(id=pk)
#     form = LeadModelForm(instance=lead)
#     if request.method == "POST":
#         form = LeadModelForm(request.POST, instance=lead)
#         if form.is_valid():
#             form.save()
#             return redirect("/leads")
#     context = {
#         'form': form,
#         'lead': lead
#     }
#     return render(request, "leads/lead_update.html",context)
class LeadDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "leads/lead_delete.html"
    def get_queryset(self):
        user=self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            queryset = queryset.filter(agent__user=user)
        return queryset
    def get_success_url(self):
        return reverse_lazy("leads:lead-list")

# def lead_delete(request, pk):
#     lead = Lead.objects.get(id=pk)
#     lead.delete()
#     return redirect("/leads")

# def lead_update(request, pk):
#     lead = Lead.objects.get(id=pk)
#     form = LeadForm()
#     if request.method == "POST":
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             lead.first_name=first_name
#             lead.last_name=last_name
#             lead.age=age
#             lead.save()
#             return redirect("/leads")
#     context = {
#         'form':form
#     }
#     return render(request, "leads/lead_update.html",context)

# def lead_create(request):
#     form = LeadForm()
#     if request.method == "POST":
#         print(request.POST)
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent= Agent.objects.first()
#             Lead.objects.create(
#                 first_name=first_name,
#                 last_name=last_name,
#                 age=age,
#                 agent=agent,
#             )
#             return redirect("/leads")
#     context = {
#         "form": form
#     }
#     return render(request, "leads/lead_create.html",context)

leads/templates/leads/lead_create.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'leads:lead-list' %}">back</a>
    <h1>Create a new lead</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'leads:lead-list' %}">back</a>
    <h3>Are You Sure You Want To Delete?</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-warning" type="submit" value="Yes, I am sure" />
    </form>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://www.8days.sg/image/12905252/3x4/720/960/5079d465bfb7968a9295d480c93d8f26/hw/hail-the-judge.jpg">
                <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD NAME</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{lead.first_name}} {{lead.last_name}}</h1>
                    <p class="leading-relaxed">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam indxgo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean shorts keytar banjo tattooed umami cardigan.</p>
                    <div class="flex">
                    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href="{% url 'leads:lead-update' lead.pk %}" style="color:white; text-decoration:inherit;">Update</a></button>
                    <button class="btn-danger flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href="{% url 'leads:lead-delete' lead.pk %}" style="color:white; text-decoration:inherit;">Delete</a></button>
                    </div>
                </div>
            </div>
    </div>

</section>

{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}
{% block content %}

<a class="btn btn-primary" href="{% url 'leads:lead-create' %}" role="button">Create New Lead</a>
    <hr/>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Lead Team</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Meet Our Lead Members!</p>
    </div>

    <div class="flex flex-wrap -m-2">
        {% for lead in leads %}
          <div class="p-2 lg:w-1/3 md:w-1/2 w-full">
            <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
              <img alt="team" class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-4" src="http://img.wxcha.com/m00/dd/7c/556721cf984da39a748855c7d8eb1c0c.jpg?down">
              <div class="flex-grow">
                <h2 class="text-gray-900 title-font font-medium"><a href="{% url 'leads:lead-detail' lead.pk %}" style="color:Black; text-decoration:inherit;">{{lead.first_name}} {{lead.last_name}}</a></h2>
                <p class="text-gray-500">Team Lead</p>
              </div>
            </div>
          </div>
        {% endfor %}
    {% if inassigned_leads.exists %}
    <h1>Unassigned Leads</h1>
    <div class="flex flex-wrap -m-2">
        {% for inassigned_lead in inassigned_leads %}
          <div class="p-2 lg:w-1/3 md:w-1/2 w-full">
            <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
              <img alt="team" class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-4" src="http://img.wxcha.com/m00/dd/7c/556721cf984da39a748855c7d8eb1c0c.jpg?down">
              <div class="flex-grow">
                <h2 class="text-gray-900 title-font font-medium"><a href="{% url 'leads:lead-detail' lead.pk %}" style="color:Black; text-decoration:inherit;">{{lead.first_name}} {{lead.last_name}}</a></h2>
                <p class="text-gray-500">Team Lead</p>
              </div>
            </div>
          </div>
        {% endfor %}
    {% endif %}
    </div>
  </div>
</section>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% block content %}
<div class="mb-3">
    <a href="/leads">back</a>
    <h1>Update lead: {{lead.first_name}} {{lead.last_name}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn btn-primary' type="submit">Submit</button>
    </form>
{% endblock content %}