agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView,AgentDeleteView


app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('agent_create/', AgentCreateView.as_view(), name='agent-create' ),
    path('<int:pk>/', AgentDetailView.as_view(), name="agent-detail"),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name="agent-update"),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name="agent-delete"),
] 

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from leads.views import LandingPageView, landing_page, SignupView
from django.contrib import admin
from django.urls import path, include
from leads.views import landing_page
from django.contrib.auth.views import LoginView,LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace="agents")),
    # password reset form template is not being triggered for some reason
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()
class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ( 
            'email',
            'username',
            'first_name',
            'last_name',
        
        )

agents/views.py
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganizerAndLoginRequiredMixin
from django.core.mail import send_mail
class AgentListView(OrganizerAndLoginRequiredMixin, generic.ListView):
    template_name = 'agents/agent_list.html'

    def get_queryset(self):
        request_user_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=request_user_organization)

class AgentCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse_lazy("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password("yuchengzhi1") 
        user.save()
        Agent.objects.create(
            user = user,
            organization = self.request.user.userprofile
        )
        send_mail(
            subject='You are invited to be an agent',
            message="this is a message!",
            from_email="sdsd@123.com",
            recipient_list=[user.email]

        )
        return super(AgentCreateView, self).form_valid(form)

class AgentDetailView(LoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"
    
    def get_queryset(self):
        request_user_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=request_user_organization)

class AgentUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse_lazy("agents:agent-list")
    def get_queryset(self):
        return Agent.objects.all()

class AgentDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_success_url(self):
        return reverse_lazy("agents:agent-list")
    def get_queryset(self):
        request_user_organization = self.request.user.userprofile
        return Agent.objects.filter(organization=request_user_organization)

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'agents:agent-list' %}">back</a>
    <h1>Create a new Agent</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'agents:agent-list' %}">back</a>
    <h3>Are You Sure You Want To Delete?</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-warning" type="submit" value="Yes, I am sure" />
    </form>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://www.8days.sg/image/12905252/3x4/720/960/5079d465bfb7968a9295d480c93d8f26/hw/hail-the-judge.jpg">
                <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">Angent Name</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{agent.user.first_name}} {{agent.user.last_name}}</h1>
                    <p class="leading-relaxed">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam indxgo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean shorts keytar banjo tattooed umami cardigan.</p>
                    <div class="flex">
                    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href="{% url "agents:agent-update" agent.pk %}" style="color:white; text-decoration:inherit;">Update</a></button>
                    <button class="btn-danger flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href="{% url "agents:agent-delete" agent.pk %}" style="color:white; text-decoration:inherit;">Delete</a></button>
                    </div>
                </div>
            </div>
    </div>

</section>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}
{% block content %}

<h1>Our Angents!</h1>
    <a class="btn btn-primary" href="{% url 'agents:agent-create' %}" role="button">Create New Agent</a>
    <hr/>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Agent Team</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Meet Our Agents</p>
    </div>

    <div class="flex flex-wrap -m-2">
        {% for agent in object_list %}
          <div class="p-2 lg:w-1/3 md:w-1/2 w-full">
            <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
              <img alt="team" class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-4" src="http://img.wxcha.com/m00/dd/7c/556721cf984da39a748855c7d8eb1c0c.jpg?down">
              <div class="flex-grow">
                <h2 class="text-gray-900 title-font font-medium"><a href="{% url 'agents:agent-detail' agent.pk %}" style="color:Black; text-decoration:inherit;">{{ agent.user.first_name }} {{ agent.user.last_name }}</a></h2>
                <p class="text-gray-500">Agent</p>
              </div>
            </div>
          </div>
        {% endfor %}
    </div>
  </div>
</section>
    {% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% block content %}
<div class="mb-3">
    <a href="/agents">back</a>
    <h1>Update Agent: {{agent.user.username}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn btn-primary' type="submit">Submit</button>
    </form>
{% endblock content %}