agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView,AgentDeleteView


app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('agent_create/', AgentCreateView.as_view(), name='agent-create' ),
    path('<int:pk>/', AgentDetailView.as_view(), name="agent-detail"),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name="agent-update"),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name="agent-delete"),
] 

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from leads.views import LandingPageView, landing_page, SignupView
from django.contrib import admin
from django.urls import path, include
from leads.views import landing_page
from django.contrib.auth.views import LoginView,LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace="agents")),
    # password reset form template is not being triggered for some reason
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from django.views.generic.list import ListView
from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView

app_name = "leads"
urlpatterns = [
    path('', LeadListView.as_view(), name="lead-list"),
    path('<int:pk>/', LeadDetailView.as_view(), name="lead-detail"),
    path('create/', LeadCreateView.as_view(), name="lead-create"),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name="lead-update"),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name="lead-delete"),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AngusCRM</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    

    <h1 class="text-center"><a href="{% url 'landing-page' %}" style="color:#0099ff; text-decoration:inherit;">AngusCRM</a></h1>
</head>
<body>
    {% include 'navbar.html' %}

    <div class="col bg-light" style="padding:12px 20px;">
        {% block content %}
        {% endblock content %}
    </div>
    {% include "script.html" %}
</body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content%}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap items-center">
    <div class="lg:w-3/5 md:w-1/2 md:pr-16 lg:pr-0 pr-0">
      <h1 class="title-font font-medium text-3xl text-gray-900">Slow-carb next level shoindcgoitch ethical authentic, poko scenester</h1>
      <p class="leading-relaxed mt-4">Poke slow-carb mixtape knausgaard, typewriter street art gentrify hammock starladder roathse. Craies vegan tousled etsy austin.</p>
    </div>
    <div class="lg:w-2/6 md:w-1/2 bg-gray-100 rounded-lg p-8 flex flex-col md:ml-auto w-full mt-10 md:mt-0">
      <h2 class="text-gray-900 text-lg font-medium title-font mb-5">Sign Up</h2>
      <div class="relative mb-4">
        <label for="full-name" class="leading-7 text-sm text-gray-600">Full Name</label>
        <input type="text" id="full-name" name="full-name" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class="relative mb-4">
        <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
        <input type="email" id="email" name="email" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <button class="text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
      <p class="text-xs text-gray-500 mt-3">Literally you probably haven't heard of them jean shorts.</p>
    </div>
  </div>
</section>
{% endblock %}

templates/navbar.html
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
 
 <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'landing-page' %}">AngusCRMs</a>

                <div class="navbar-collapse collapse" id="collapseNavbar">
            <ul class="navbar-nav">
                {% if request.user.is_organizer %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'agents:agent-list' %}">List of Agents</a>
                </li>
                {% endif %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'leads:lead-list' %}">List of Leads</a>
                </li>
          
                
            </ul>
        </div>
        {% if request.user.is_authenticated %}
        Hello {{ request.user.username }}
            <a class="nav-link" href="{% url 'logout' %}"> <i class="bi bi-box-arrow-in-right"> Log out</i></a>
        {% else %}
        <div class="float-right" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
            <li class="nav-item ">
            <a class="nav-link" href="{% url 'signup' %}" ><i class="bi bi-person-plus"> Sign Up</i></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}"> <i class="bi bi-box-arrow-in-right"> Login</i></a>
            </li>
        </ul>
        </div>
        {% endif %}
    </div>
    </nav>

templates/script.html
{% load static %}

<script src="{% static 'js/main.js' %}" >  </script>

templates/second_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    222222
</body>
</html>